name: build

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to create'
        required: true
        default: 'v0.0.0'

# See https://github.com/cristalhq/.github/.github/workflows
jobs:
  build:
    permissions: read-all
    uses: cristalhq/.github/.github/workflows/build.yml@96edb7a4323a57e1971a3fbb778417aed97d92da # v0.1.0

  release:
    if: github.event_name == 'workflow_dispatch'
    uses: cristalhq/.github/.github/workflows/release.yml@96edb7a4323a57e1971a3fbb778417aed97d92da # v0.1.0
    permissions: 
      contents: write
    with:
      tag: ${{ github.event.input.tag }}
