name: build

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to create'
        required: true
        default: 'v0.0.0'

# See https://github.com/cristalhq/.github/.github/workflows
jobs:
  build:
    permissions: read-all
    uses: cristalhq/.github/.github/workflows/build.yml@0231b807f746a1e46fe1ef279acd444f12b137c5 # v0.2.2

  release:
    if: github.event_name == 'workflow_dispatch'
    uses: cristalhq/.github/.github/workflows/release.yml@0231b807f746a1e46fe1ef279acd444f12b137c5 # v0.2.2
    permissions: 
      contents: write
    with:
      tag: ${{ github.event.input.tag }}
