name: build

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to create'
        required: true
        default: 'v0.0.0'

# See https://github.com/cristalhq/.github/.github/workflows
jobs:
  build:
    permissions: read-all
    uses: cristalhq/.github/.github/workflows/build.yml@02d6a2a176fc4c22e5d84c2636f8a62e53dc17a4 # v0.2.0

  release:
    if: github.event_name == 'workflow_dispatch'
    uses: cristalhq/.github/.github/workflows/release.yml@02d6a2a176fc4c22e5d84c2636f8a62e53dc17a4 # v0.2.0
    permissions: 
      contents: write
    with:
      tag: ${{ github.event.input.tag }}
