name: build

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to create'
        required: true
        default: 'v0.0.0'

# See https://github.com/cristalhq/.github/.github/workflows
jobs:
  build:
    permissions: read-all
    uses: cristalhq/.github/.github/workflows/build.yml@2af24ae1cecb6f3e87771a200479a053bd76ee34 # v0.3.0

  release:
    if: github.event_name == 'workflow_dispatch'
    uses: cristalhq/.github/.github/workflows/release.yml@2af24ae1cecb6f3e87771a200479a053bd76ee34 # v0.3.0
    permissions: 
      contents: write
    with:
      tag: ${{ github.event.input.tag }}
